# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, katago, stdenv, globalBuildInputs ? []}:

let
  sources = {
    "@sabaki/gtp-3.0.0" = {
      name = "_at_sabaki_slash_gtp";
      packageName = "@sabaki/gtp";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sabaki/gtp/-/gtp-3.0.0.tgz";
        sha512 = "faMAB9pTz2lIPUQz0dNV5IcA+bagRZYldGdCr7/Bl7dqJ3A/4FkspqrcTkM1LgZZ0xctbQRKedkpqhkORitw6A==";
      };
    };
  };
  modifiedSource = stdenv.mkDerivation {
    name = "katajigo-source";
    version = "1.0.2";
    src = builtins.fetchGit {
      url = "https://github.com/yishn/KataJigo.git";
    };
    phases = [ "buildPhase" ];

    buildPhase = ''
      mkdir $out
      cp -R $src/* $out
      chmod -R 777 $out/*
      sed -i -e $'s@join(dirname(process.execPath), \'katago\')@"${katago}/bin/katago"@' $out/src/main.js
      cat $out/src/main.js
    '';
  };
  args = {
    name = "katajigo";
    packageName = "katajigo";
    version = "1.0.2";
    src = modifiedSource;
    dependencies = [
      sources."@sabaki/gtp-3.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "";
      homepage = "https://github.com/yishn/KataJigo#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}
